services:
  vertacoo_core.form_errors_serializer:
    class: Vertacoo\CoreBundle\Service\FormErrorsSerializer

    vertacoo_core.fieldset.type:
        class: Vertacoo\CoreBundle\Form\Type\FieldsetType
        arguments: []
        tags:
            - { name: form.type }